### ISSUE TITLE
Zimbra Desktop 7.2.8 / Build 12093

### ISSUE THREAD

**Issue by MyLive** [Zimbra-Community/com_zimbra_emailtemplates#1]
Hello @ all,

the Plugin does not work on ZD 7.2.8.
If i click new Mail, the ZD does nothing.

Can anyone fix this please.

Thanks a lot

**Comment by barrydegraaff** [comment]
Thanks for your issue report, at this time I do not support ZD. But I will leave issue open, and see if someone picks it up.
