### ISSUE TITLE
Calendar templates

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/com_zimbra_emailtemplates#11]
The old version of this zimlet supported Calendar/Appointment templates, but that feature was never fixed for 8.x

old version:
https://zimbra.org/extend/items/view/email-templates

**Comment by barrydegraaff** [comment]
removed from the code

**Comment by sparadrus** [comment]
Hello Barry,
It's possible to re-implement this function ? Is very useful for us, our secretary service used template appointement 500+ per day.
We must downgrade to 0.9.3, and we wish upgrade the zimlet.
Best Regards,
Philippe
