### ISSUE TITLE
feature request - email recipient

### ISSUE THREAD

**Issue by bgordon1024** [Zimbra-Community/com_zimbra_emailtemplates#13]
Not sure if it does this already or if it is even possible.  Basically I would like to have the template replace {suchandsuch}@whatever.com

My email-to-fax software requires the recipient's fax number to be {faxnumber}@whatever.com as the sent-to address, and it uses the body of the email message as a cover page. Ideally I would like to have the template replace {faxnumber} in the sending-to email address and in the body {to} for the cover page.

I didn't word this very well, but do you understand what I am asking?

**Comment by barrydegraaff** [comment]
At this time it does not work that way, as
it would not allow to replace something in the
recipients.

Not sure if it ever did...

**Comment by bgordon1024** [comment]
I'll still use it for the email body cover page. Thank you!
