### ISSUE TITLE
Support for 8.8.15

### ISSUE THREAD

**Issue by Gulaschcowboy** [Zimbra-Community/com_zimbra_emailtemplates#17]
Hi,

release 1.0.1 doesn't seem to work for Zimbra Network 8.8.15. The zimlet doesn't apperar in the Zimlet Section.

Is it a known issue?

**Comment by barrydegraaff** [comment]
You must enable it in the users COS in the admin interface.

**Comment by Gulaschcowboy** [comment]
Hi Barry,

sure, it is enabled in the COS and in the users settings, but it doesn't appear.

**Comment by barrydegraaff** [comment]
It should only show as a button when composing an email.

It is tested on 8.8.15

**Comment by Gulaschcowboy** [comment]
Hi Barry,

thank you, I missed that fact.
