### ISSUE TITLE
Zimbra 9 support?

### ISSUE THREAD

**Issue by tdb85** [Zimbra-Community/com_zimbra_emailtemplates#19]
Hi, 
Just found this Zimlet and excited to try it out.  We are currently on 8.8.15 but have plans to upgrade Zimbra to 9.0 in the near future.
Will this Zimlet work on 9.0.0?

**Comment by barrydegraaff** [comment]
This Zimlet does not support Zimbra 9, but there is a similar zimlet 
that does:

https://github.com/Zimbra/zimbra-zimlet-email-templates
