### ISSUE TITLE
Saving a template without a Subject sends the message instead

### ISSUE THREAD

**Issue by DSpeichert** [Zimbra-Community/com_zimbra_emailtemplates#3]
When trying to Save a template without subject I expected to see the message `EmailTemplatesZimlet_noSubject`.

Instead, the web interfaces offers to send the message (`Warning! No subject. Send anyway?`) and it actually does!

When the subject is filled in, the template gets saved properly.

**Comment by barrydegraaff** [comment]
Thanks for reporting, I will look into this, later this week.

**Comment by barrydegraaff** [comment]
Unfortunately I do not think there is an easy way to fix it. 

The only way would be to use a 'New' button somewhere that would set up a new draft message. The behavior we see here, is how it was built... meaning the compose tab does not know in advance if we are writing an email or if we are creating a template.

Then the templates zimlet has no way to get the draft message, as Zimbra refuses to create one, if there is no subject/recipient.

So all-in-all I think this will be a wontfix. Sorry.

**Comment by barrydegraaff** [comment]
On the other hand, maybe there is some out-of-date code in this zimlet, so I'll look some more

**Comment by 5points-brandon** [comment]
It looks like the pull request I submitted will correct (although not the issue I was working on).  It also allows saving templates with out a to or cc.  More testing probably needs to be done.

https://github.com/Zimbra-Community/com_zimbra_emailtemplates/pull/6

**Comment by barrydegraaff** [comment]
@DSpeichert this issue is fixed in the latest release

**Comment by DSpeichert** [comment]
Thank you, @barrydegraaff . You may have forgotten the PL language in release notes, unless it was omitted from the package.

**Comment by barrydegraaff** [comment]
The PL was added in, the release notes are a bit skinny.
