### ISSUE TITLE
Reloading templates sets search string

### ISSUE THREAD

**Issue by Napkin** [Zimbra-Community/com_zimbra_emailtemplates#5]
Hi there,
Whenever the templates are reloaded from the configured mail folder (automatically after changing zimlet configuration or when manually selecting "Reload Templates") the text in Zimbra's search bar in the top-right is changed to:
`in:("<template folder>")`
In my case the text changes to `in:("Templates")` as that's what I chose as mail folder for templates.

I think this internal search should not be shown to the user and not overwrite their previous searches.

Details:
Zimbra Version: 8.7.1_GA_1670.NETWORK
Zimlet Version: 0.8 (I think corresponds to commit 292a89f)

Thanks for this zimlet and for choosing the open-source path.

Best wishes,
Marc

**Comment by barrydegraaff** [comment]
I have seen this as well, whenever a reload occurs, something is going on in the search. It is something new in 8.7.

**Comment by barrydegraaff** [comment]
This seems to work as designed, so I won't be patching it.
