### ISSUE TITLE
Templates Listing Limited to 25 Templates

### ISSUE THREAD

**Issue by 5points-brandon** [Zimbra-Community/com_zimbra_emailtemplates#9]
The Templates list appears to be limited to 25 templates.  After a 26th is added the oldest template falls off the list.

**Comment by barrydegraaff** [comment]
I can confirm this issue, it appears somebody hardcoded a hard-limit of 25 in:
https://github.com/Zimbra-Community/com_zimbra_emailtemplates/blob/master/com_zimbra_emailtemplates/emailtemplates.js#L104

Which is pretty boring, but I guess nobody ever used over 25 templates before.

**Comment by 5points-brandon** [comment]
Interesting.  Should this simply be a larger number?  I am not familiar with what would happen on smaller screens if the list did not fit.  If memory serves me from a previous bug that would double the list, it would add another column next to it for growth.  Or create a properties option to set the upper limit?

**Comment by barrydegraaff** [comment]
Well, I have a feeling that its has something do to with the menu, not being able to deal with more than 25 items.

I will test in a moment.

**Comment by barrydegraaff** [comment]
Seems to work fine, while I could remove the limit, it's probably safer to increment it.

For now I am putting it to 50. New release added.
